services:
  authenticate:
    build: ./AuthService
    ports:
      - "5001:80"
  
  database:
    build : ./DatabaseService
    ports:
      - "5002:80"
        
  manage:
    build: ./ManageService
    ports:
      - "5003:80"
  
  task:
    build: ./TaskService
    ports:
      - "5004:80"
        
  user:
    build: ./UserService
    ports:
      - "5005:80"
  
  